wheel/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
from .models import User
from .forms import RegisterForm
from flask_login import login_required,logout_user
from . import db


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['POST'])
def login(): 
    email = request.form['email']
    password = request.form['password']

    if email and password:
        success, message = User.login(email, password)
        flash( message, 'success' if success else 'danger')
            
    return redirect(url_for('main.index'))




@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if (form.validate_on_submit()):
        name = form.name.data
        email = form.email.data
        password = form.password.data

        if not User.register(name, email, password):
            flash('User name already exists', 'danger')
            return redirect(url_for('auth.login'))

        flash('Thanks for registering! Please log in', 'success')
        return redirect(url_for('main.index'))

    return render_template('register.html', form=form)



@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

wheel/controllers/accounts.py
from flask import Blueprint, redirect, render_template, url_for, flash
from flask_login import current_user, login_required

from wheel.models import User

accounts = Blueprint('accounts', __name__, url_prefix='/accounts')


@accounts.route('/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    if id == current_user.id:
        flash(f'Cannot delete account that is logged in.', 'danger')
        return redirect( url_for('accounts.get'))

    User.delete(id)

    flash(f'Successfully deleted account', 'success')
    return redirect( url_for('accounts.get') )



@accounts.route('/<int:id>/admin', methods=['GET', 'POST'])
@login_required
def admin(id):
    User.makeAdmin(id)

    flash(f'Successfully made account an administrator', 'success')
    return redirect( url_for('accounts.get') )



@accounts.route('/')
@login_required
def get():
    users = User.query.all()

    return render_template('accounts.html', users=users)

wheel/controllers/bookings.py
from datetime import datetime

from flask import Blueprint, render_template
from flask_login import current_user, login_required

from wheel.models import Booking

bookings = Blueprint('bookings', __name__, url_prefix='/bookings')


@bookings.route('/<int:id>')
@bookings.route('/')
@login_required
def get(id=None):
    if id:
        booking = Booking.get(id)
        ticket = booking.getTicket()
        event = booking.getEvent()

    bookings = [[booking, ticket, event]] if id else \
        [[booking, booking.getTicket(), booking.getEvent()] for booking in Booking.getAllByUser(current_user.id)]

    return render_template('bookings.html', bookings=bookings, now=datetime.now() )

wheel/controllers/events.py
import json
from datetime import datetime

from flask import Blueprint, redirect, render_template, request, url_for
from flask.helpers import flash
from flask_login import current_user, login_required

from wheel.forms import SearchForm, CreateEventForm, BookEventForm, PostReviewForm
from wheel.models import Event, Ticket, Booking, Review
from wheel.forms import check_upload_file

events = Blueprint('events', __name__, url_prefix='/events')


@events.route('/<int:id>/update', methods=['GET', 'POST'])
@events.route('/create', methods=['GET', 'POST'])
@login_required
def create(id=None):
    if not current_user.is_admin():
        flash( "You are not an administrator. You can't create or update events", 'danger' )
        return redirect( url_for('index.get') )

    form = CreateEventForm() 
    form.category.choices = [("", "new category"), *[(category, category) for category in Event.getAllCategories()]]

    if form.validate_on_submit(): 
        # POST goes this way
        existing_event = Event.get(id) if id else False
        
        name = form.name.data
        description = form.desc.data
        existing_category = form.category.data
        category = existing_category if existing_category else form.newcategory.data
        status = form.status.data
        image = check_upload_file(form.image.data)
        jsonTickets = form.tickets.data

        event = existing_event.set(name, description, category, status, image) if existing_event else \
                Event.create(name, description, category, status, image)

        if jsonTickets:
            tickets = json.loads(jsonTickets)

            if existing_event: 
                event.deleteAllTickets()

            for ticket in tickets:
                datetimeobj = datetime.strptime(ticket["datetime"], '%Y-%m-%d %H:%M'),
                Ticket.release( event.id, datetimeobj, ticket["numberOfGondolas"], ticket["price"] )

        flash(f'Successfully created {form.name.data}', 'success')
        return redirect( url_for('events.get', id=event.id))

    # GET goes this way 
    form.changeDefaultStatus = lambda status: changeDefaultStatus(status)
    def changeDefaultStatus(status):
        form.status.default = status
        form.process()
        return form.status

    if id:
        # UPDATE
        event = Event.get(id)
        tickets = [ { 
            "date": date, 
            "tickets": [ {
                "remaining": ticket.remaining, 
                "price": ticket.price
            } for ticket in tickets]
        } for date, tickets in Ticket.groupTicketsByDate(event.tickets) ]

        form.name.data = event.name
        form.desc.data = event.description
        form.image.data = event.image
        form.status.data = event.status
        form.category.data = event.category
        form.newcategory.data = event.category

        return render_template('create.html', form=form, event_id=id, tickets=json.dumps(tickets) )
    
    # CREATE
    now = datetime.now().strftime("%Y-%m-%d")
    return render_template('create.html', form=form, event_id=id, now=now)
    


@events.route('/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    event = Event.get(id)
    event.delete()

    flash(f'Successfully deleted event', 'success')
    return redirect( url_for('events.getAll') )



@events.route('/<int:id>/book', methods=['POST'])
@login_required
def book(id):
    form = BookEventForm()
    event = Event.get(id)
    form.ticket.choices = list(map(lambda ticket: (ticket.id, f'${ticket.price}'), event.getFutureTickets()))

    if form.validate_on_submit():    
        qty = form.qty.data
        total_price = form.price.data
        purchase_datetime = datetime.now()
        user_id = current_user.id
        ticket_id = form.ticket.data      

        error, remaining, booking_id = Booking.book(qty, total_price, purchase_datetime, user_id, ticket_id)

        if error:
            flash(f'Sorry, there are only {remaining} gondolas available for that time, please try again.', 'danger')
            return redirect( url_for('events.get', id=event.id)) 
        
        flash(f'Successfully booked {qty} tickets. Your booking ID is: {booking_id}', 'success')
        return redirect( url_for('bookings.get') )

    flash(f'Sorry, you cannot book an event with no availability.', 'danger')
    return redirect( url_for('index.get') )



@events.route('/<int:id>/review', methods=['POST'])
@login_required
def review(id):
    form = PostReviewForm() 
    event = Event.query.get(id)

    if form.validate_on_submit(): 
        Review.post(event.id, current_user.id, form.text.data)
        flash('Review Created!', 'success')
        
    else:
        flash('Issue posting review', 'danger')

    return redirect( url_for('events.get', id=id))



@events.route('/<int:id>')
def get(id):
    event = Event.get(id)
    if event is None:
        return render_template('eventnotfound.html')
    tickets = event.getFutureTickets()

    if len(tickets) == 0:
        if event.status != 'cancelled':
            event.updateStatus("inactive")
        
    times = Ticket.getAllTimesFromTickets(tickets)
    dates = Ticket.groupTicketsByDate(tickets)

    bookform = BookEventForm()
    reviewform = PostReviewForm() 
    bookform.ticket.choices = list(map( lambda ticket: (ticket.id, f'${ticket.price}'), tickets ))

    # in the template, 
    # times are used to generate the table header and
    # dates are used to generate rows.
    # the radio options are not actually held in dates, 
    # rather, they are retreived from the form object according to the ticket ids in dates
    return render_template('event.html', event=event, bookform=bookform, times=times, dates=dates, reviewform=reviewform)


@events.route('/')
def getAll():
    search = request.args['search'] if 'search' in request.args else ''
    category = request.args['category'] if 'category' in request.args else 'all'
    categories = Event.getAllCategories()

    if search == '' and category == 'all':
        events = Event.getAll()

    elif search == '':
        events = Event.getAllByCategory(category)

    elif category == 'all':
        events = Event.getAllBySearch(search)

    else:
        events = Event.getAllBySearchAndCategory(search, category)

    form = SearchForm() 
    form.category.choices = [("all", "all categories"), *[(category, category) for category in Event.getAllCategories()]]
    form.search.data = search
    form.category.data = category
    
    return render_template('events.html', events=events, categories=categories, form=form)

wheel/templates/405.html
{% extends 'base.html' %}

{% block title %}Access Denied{% endblock %}

{% block content %} 
<a class="nav-link" href="{{ url_for('index.get') }}">Click here to return to the home page</a>
{% endblock %}

wheel/templates/accounts.html
{% extends 'base.html' %}

{% block title %}Accounts List{% endblock %}

{% block content %}

<section class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4 mb-3">
    <h1>Admins: </h1>
    
        {% for user in users %}
        
            {% if user.type == 'administrator' %}
            <div id="{{ user.id }}" class="col">
                <div class="card">
                    
                    <div class="card-body">
                        <div class="card-body">
                            <h5>{{ user.name }}</h5>
                            <div><strong>User ID: </strong>{{ user.id }}</div>
                            <div><strong>email: </strong>{{ user.email }}</div>
                            <div class="col-sm-auto my-auto">
                                <a href="{{ url_for('accounts.delete', id=user.id) }}" class="btn btn-outline-primary rounded-pill px-5">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    
</section>
<section class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-4 mb-3">

    <h1>Customers: </h1>

    

        {% for user in users %}

            {% if user.type == 'customer' %}
            <div id="{{ user.id }}" class="col">
                <div class="card">
                    
                    <div class="card-body">
                        <div class="card-body">
                            <h5>{{ user.name }}</h5>
                            <div><strong>User ID: </strong>{{ user.id }}</div>
                            <div><strong>email: </strong>{{ user.email }}</div>
                            <div class="col-sm-auto my-auto">
                                
                            </div>
                            <div class="col-sm-auto my-auto">
                                <a href="{{ url_for('accounts.delete', id=user.id) }}" class="btn btn-outline-primary rounded-pill px-5">Delete</a>
                                <a href="{{ url_for('accounts.admin', id=user.id) }}" class="btn btn-outline-primary rounded-pill px-5">Make Admin</a>
                            </div>
                            
                            
                        </div>
                    </div>
                </div>
            </div>

            {% endif %}
        {% endfor %}
    
</section>
{% endblock %}

wheel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Wheel of Brisbane Event Manager</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" 
            integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
            rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/unbootstrapify.css">
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light justify-content-between">
                <div class="navbar-nav flex-row gap-3">
                    <a class="nav-link" href="{{ url_for('index.get') }}">Home</a>
                    <a class="nav-link" href="{{ url_for('events.getAll') }}">Events</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('bookings.get') }}">My Bookings</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                    {% if current_user.is_authenticated and current_user.is_admin() %}
                    <a class="nav-link" href="{{ url_for('accounts.get') }}">Accounts</a>
                    {% endif %}
                </div>
                <button class="navbar-toggler" type="button" 
                        data-bs-toggle="collapse" data-bs-target="#navbarlogin">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse flex-grow-0" id="navbarlogin">
                    {% if not current_user.is_authenticated %}
                    <form method="POST" action="{{ url_for('auth.login') }}" class="navbar-nav flex-row gap-1">
                        {# form.hidden_tag() #}
                        <input name="email" type="text" required 
                                class="form-control" placeholder="email address">
                        <input name="password" type="password" required 
                                class="form-control" placeholder="password">
                        <button class="btn btn-outline-success rounded-pill px-5" type="submit">Login</button>
                    </form>
                    {% else %}
                    <form action="{{ url_for('auth.logout') }}" class="navbar-nav flex-row gap-1">
                        {# form.hidden_tag() #}
                        <button class="btn btn-outline-primary rounded-pill px-5" type="submit">Logout</button>
                    </form>
                    {% endif %}
                </div>
            </nav>
            <div>
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{category}}">{{message}}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            {% block hero %}
            {% endblock %}
        </header>
        <main>
            <header class="row mb-3">
                <div class="col-md">
                    <h1>{% block title %}{% endblock %}</h1>
                </div>
                {% block header_buttons %}{% endblock %}
            </header>
            {% block content %}
            {% endblock %}
        </main>
        <footer class="mt-5 text-center footer"><strong>not endorsed by or associated with </strong>The Wheel of Brisbane Pty Ltd</footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" 
            crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

wheel/templates/event.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block hero %}
<div id="minihero" style="background-image: url('{{ event.image }}');"></div>
{% endblock %}

{% block title %}{{ event.name }}{% endblock %}

{% block header_buttons %}
    {% if current_user.is_authenticated and current_user.is_admin() %}
        <div class="col-sm-auto my-auto">
            <a href="{{ url_for('events.create', id=event.id) }}" class="btn btn-outline-primary rounded-pill px-5">Update</a>
        </div>
    {% endif %}

    {% if current_user.is_authenticated and current_user.is_admin() %}
        <div class="col-sm-auto my-auto">
            <a href="{{ url_for('events.delete', id=event.id) }}" class="btn btn-outline-primary rounded-pill px-5">Delete</a>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
<section>
    <h4><a href="{{ url_for('events.getAll') + '?category=' + event.category }}" class="text-decoration-none text-muted">{{ event.category }}</a></h4>
</section>
<section class="mb-3">
    {{ event.description }}
</section>
<section>    
    <header class="row mb-3">
        <h3 class="col">Dates and times</h3>
        <!-- <span class="col-sm-auto ms-auto my-auto">{{ event.status }}</span> -->
    </header>
    <div class="row mb-3">
        <div class="col-sm">
            <p class="mb-1">
                {{ event.printTicketsDateRange() }}
            </p>
        </div>
        <div class="col-sm">
            <p class="mb-1">
                {{ event.printTicketsTimeRange() }}
            </p>
        </div>
        <div class="col-sm">
            <p>{{ event.getTicketsPriceFrom() }}</p>
        </div>
        <div class="col-sm-auto my-auto">
            {% if current_user.is_authenticated %}
                <button type="button" class="btn btn-outline-{{ event.getStatusColour() }} rounded-pill px-5" 
                        data-bs-toggle="modal" data-bs-target="#book" {{ "disabled" if event.status != 'upcoming' }}>{{ event.getBookButtonText() }}</button>
            {% else %}
                <button type="button" class="btn btn-outline-{{ event.getStatusColour() }} rounded-pill px-5" 
                        data-bs-toggle="tooltip" data-bs-placement="top" 
                        title="You must be logged in to book tickets"
                        {{ "disabled" if event.status != 'upcoming' }}>{{ event.getBookButtonText() }}</button>
            {% endif %}
        </div>
    </div>

    

    <div id="book" class="modal fade" tabindex="-1" 
            data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog modal-lg">
            <form class="modal-content" method="POST" action="{{ url_for('events.book', id=event.id ) }}">
                {{ bookform.hidden_tag() }}
                <div class="modal-header">
                    <h5 id="staticBackdropLabel" class="modal-title">Book your tickets to {{ event.name }} on the Wheel of Brisbane</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <fieldset class="row row-cols-{{ times|length+1 }} mb-3 btn-group g-2 gx-lg-5">
                        <legend class="col-12 col-lg">Dates and times</legend>
                        <span class="col-12 col-lg-auto my-auto">Prices listed are per gondola. Max 6 people</span>
                        <div class="w-100"></div>
                        <!-- times header -->
                        <div class="col"></div>
                        {% for time in times %}
                            <div class="col">
                                <label class="btn btn-light rounded-pill w-100">{{time}}</label>    
                            </div>
                        {% endfor %}
                        <!-- new date row -->
                        {% for date, tickets in dates %}
                            <div class="col">
                                <label class="btn btn-light rounded-pill w-100">{{date}}</label>    
                            </div>
                            {% for ticket in tickets %}
                            {% set remaining = ticket.remaining %}
                                {% for radioOption in bookform.ticket if radioOption.data == ticket.id %}
                                    <div class="col">
                                        {% if remaining > 0 %}
                                            {{ radioOption(class_="btn-check", data_remaining=remaining, data_price=ticket.price, required=True ) }}
                                            {{ radioOption.label(class_="btn btn-outline-success rounded-pill w-100") }}
                                        {% else %}
                                            {{ radioOption(class_="btn-check", data_price=ticket.price, disabled=True ) }}
                                            {{ radioOption.label(class_="btn btn-outline-secondary rounded-pill w-100" ) }}
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        {% endfor %}
                    </fieldset>
                    <fieldset class="row mb-3 g-2">
                        <legend class="">Passengers and Gondolas</legend>
                        <span class="">Up to 6 passengers may ride together in one gondola. You may, however, reserve as many extra gondolas for your group as you please.</span>
                        
                        <div class="col text-end">
                            <label for="people">number of people</label>
                        </div>
                        <div class="col-auto">
                            <div class="btn-group counter">
                                <button type="button" disabled
                                        class="btn btn-success rounded-pill rounded-end minus">-</button>
                                <input id="people" type="number" min="1" max="252" value="1" 
                                    class="rounded-0 border-success border-start-0 border-end-0 form-control text-center shadow-none"/>
                                <button type="button" 
                                        class="btn btn-success rounded-pill rounded-start plus">+</button>
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col text-end">{{ bookform.qty.label }}</div>
                        <div class="col-auto">
                            <div class="btn-group counter">
                                <button type="button" disabled 
                                        class="btn btn-success rounded-pill rounded-end minus">-</button>
                                {{ bookform.qty(class_="rounded-0 border-success border-start-0 border-end-0 form-control text-center shadow-none",  min="1", max="42") }}
                                <button type="button" disabled 
                                        class="btn btn-success rounded-pill rounded-start plus">+</button>
                            </div>
                        </div>
                        <div id="remainingWarning" class="w-100 text-end"></div>
                        <div class="col my-auto text-end">
                            <label for="price">price</label>
                        </div>
                        <div class="col-auto">
                            <div class="btn-group counter">
                                <span class="btn btn-success rounded-pill rounded-end">$</span>
                                {{ bookform.price(readonly=true, class_="rounded-0 border-success border-start-0 border-end-0 form-control text-center shadow-none bg-white",  min="0") }}
                                <span class="btn btn-success rounded-pill rounded-start">.00</span>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary rounded-pill px-5" 
                            data-bs-dismiss="modal">Cancel</button>
                    {{ bookform.submit(class_="btn btn-success rounded-pill px-5") }}
                </div>
            </form>
        </div>
    </div>
</section>
<section>
    <header><h2>Reviews</h3></header>
    {% if current_user.is_authenticated %}
    <form id="review" class="row mb-3" method="POST" action="{{ url_for('events.review', id=event.id) }}">
        {{ reviewform.hidden_tag() }}
        <div class="col">
            <div class="form-floating">
                {{ reviewform.text(class_="form-control", placeholder="Write a review") }}
                {{ reviewform.text.label }}
            </div>
        </div>
        <div class="col-auto my-auto">
            {{ reviewform.submit(class_="btn btn-outline-success rounded-pill px-5") }}
        </div>
    </form>
    {% endif %}
    <div id="reviews">
        {% for review in event.reviews %}
            <div class="row border-top pt-3"> 
                <article>
                    <strong>{{ review.author.name }}</strong>
                    <i>{{ review.time.strftime("%d/%m/%Y") }}</i>
                    <p>{{ review.text }}</p>
                </article>
            </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

{% block scripts %}
<script>
    (function(){
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        });
    })()
</script>
<script>
    (function(){
        const people = document.getElementById('people');
        const gondolas = document.getElementById('qty');

        /* selecting a ticket option */
        document.querySelectorAll('[name="ticket"]').forEach( (ticket) => {
            ticket.addEventListener('change', ({target}) => {
                updatePrice( target.getAttribute('data-price') || 0 );

                const warning = document.getElementById('remainingWarning');
                const remaining = target.getAttribute('data-remaining');
                warning.innerText = "There are " + remaining + " gondolas remaining for this time.";
            } )
        } )

        /* updating number of people */
        people.addEventListener('change', ({target}) => {
            const minus = target.closest('.counter').querySelector('.minus');
            minus.disabled = (target.value === target.min );

            const plus = target.closest('.counter').querySelector('.plus');
            plus.disabled = (target.value === target.max);

            const requiredgondolas = Math.ceil( Number(target.value)/6 );

            const currentgondolas = Number(gondolas.value);
            if ( currentgondolas < requiredgondolas || target.value < currentgondolas ){
                gondolas.value = requiredgondolas;
            }

            gondolas.dispatchEvent( new Event('change') );
        } );

        /* updating number of gondolas */
        gondolas.addEventListener('change', ({target}) => {
            const plus = target.closest('.counter').querySelector('.plus');
            plus.disabled = (target.value === people.value || target.value === target.max);
            
            const requiredgondolas = Math.ceil( Number(people.value)/6 );
            const minus = target.closest('.counter').querySelector('.minus');
            minus.disabled = (target.value <= requiredgondolas);

            const price = document.querySelector(`[value="${target.form.ticket.value}"]`);

            price && updatePrice( price.getAttribute('data-price') || 0 );
        } );

        /* controls for buttons */
        document.querySelectorAll('.counter').forEach( (counter) => {
            counter.querySelectorAll('button').forEach( (button) => {
                button.addEventListener('click', () => {
                    const input = counter.querySelector('input');

                    if ( button.classList.contains('plus') )
                        input.stepUp();
                    
                    if ( button.classList.contains('minus') )
                        input.stepDown();

                    input.dispatchEvent( new Event('change') );
                } );
            } );
        } );

        function updatePrice(price){
            document.getElementById('price').value = Number(gondolas.value) * Number( price );
        }
    })()
</script>

{% endblock %}

wheel/templates/eventnotfound.html
{% extends 'base.html' %}

{% block title %}Event Not Found. It may have been deleted.{% endblock %}

{% block content %} 
<a class="nav-link" href="{{ url_for('index.get') }}">Click here to return to the home page</a>
{% endblock %}

wheel/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Register{% endblock %}

{% block content %}
<div>
{{wtf.quick_form(form)}}
</div>
{% endblock %}